### ISSUE TITLE
Lower XReadMUMetaData (b4831) Signature

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/XbSymbolDatabase#161]
XReadMUMetaData (b4831) signature turns out detected in earlier build, NFL Blitz 202 title (b4242), and it is accurate match.

TASKS:
- [ ] Find out which earlier build has XReadMUMetaData symbol.
  - build 4242 is last known detected and I haven't found any titles before 4831 build.

**Comment by ergo720** [comment]
Done in https://github.com/Cxbx-Reloaded/XbSymbolDatabase/pull/163
