### ISSUE TITLE
XbSymbolDatabase wrongfully detects D3DDevice_BlockUntilVerticalBlank in the game Black

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/XbSymbolDatabase#194]
Below is the function that I was able to find with IDA, which XbSymbolDatabase currently detects at a completely different address. As a side note, this wrong detection causes the game not to boot in Cxbx-Reloaded.
![d3d](https://user-images.githubusercontent.com/45463469/223843835-0e79e5c1-d82e-45cb-bf01-1204751db84f.PNG)

**Comment by ergo720** [comment]
After more analysis, it turns out that Black has a inline version of D3DDevice_BlockUntilVerticalBlank (the one shown above), in addition to a regular non-inline version, which is the one currently detected by XbSymbolDatabase.

**Comment by RadWolfie** [comment]
Since it is inline function, XbSymbolDatabase will not provide detection for it. Cxbx-Reloaded doesn't have support for inline function patches. Closing as won't fix since non-inline version is detected correctly.

**Comment by PatrickvL** [comment]
Note, that inlined functions like these will likely require CxbxReloaded to emulate the code rather than patch it.

**Comment by PatrickvL** [comment]
See https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/2419
