### ISSUE TITLE
Titles with D3D8I and D3D8X libraries cause scan process to stuck looping

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/XbSymbolDatabase#197]
This issue only happen if D3D8X library exist in database but not D3D8I library which is actually a dependency for D3D8X library.

A better method is needed to determine if dependency library do exist or not to avoid getting stuck waiting on non-existence dependency library to complete.

**Comment by RadWolfie** [comment]
After some checking in codebase, one thing stand out.

https://github.com/Cxbx-Reloaded/XbSymbolDatabase/blob/3896aabdfc92c51989446b8359d447fa61de90af/src/lib/libXbSymbolDatabase.c#L459-L471
Above code describe as if assuming library filters were given or not.

After some considerations from looking at cli and test tools, it seems they do not need any change other than internal library's function fix. I'm thinking the first if statement will need change to `pContext->library_input.count` for count is not zero **in order to return actual dependencies even if there are none**.

**Comment by jackchentwkh** [comment]
check your idea with XDK PerfTest sample, which uses LIBs as below,
[0x4EA0] INFO : INIT    Title : PerfTest
[0x4EA0] INFO : INIT    XBE TitleID : FFFFF100
[0x4EA0] INFO : INIT    XBE TitleID (Hex) : 0xfffff100
[0x4EA0] INFO : INIT    XBE Version : 0.4096
[0x4EA0] INFO : INIT    XBE Version (Hex): 00100000
[0x4EA0] INFO : INIT    XBE TitleName : PerfTest
[0x4EA0] INFO : INIT    XBE Region : Region Free (DEBUG)
[0x4EA0] INFO : INIT    XBE Library 0 : XAPILIB (version 5849)
[0x4EA0] INFO : INIT    XBE Library 1 : D3D8I (version 5849)
[0x4EA0] INFO : INIT    XBE Library 2 : D3DX8 (version 5849)
[0x4EA0] INFO : INIT    XBE Library 3 : XGRAPHC (version 5849)
[0x4EA0] INFO : INIT    XBE Library 4 : XBOXKRNL (version 5849)
[0x4EA0] INFO : INIT    XBE Library 5 : LIBC (version 5849)

your approach works which preventing the endless loop. 
but the D3D8I library was not scanned and there is no D3D apis scanned/detected.

add LIB_D3D8I definition and force the flag to treat D3D8I as D3D8 enables the scan on D3D8I lib, and there are some apis being identified.

#define Lib_D3D8I    "D3D8I"

uint32_t XbSymbolDatabase_LibraryToFlag(const char* library_name)
{
    if (strncmp(library_name, Lib_D3D8, 8) == 0) {
        return XbSymbolLib_D3D8;
    }
    if (strncmp(library_name, Lib_D3D8I, 8) == 0) {
        return XbSymbolLib_D3D8;
    }

but not all d3d apis are identified. needs further inspection with that particular sample.
maybe we need a different set of symbol sinatures for D3D8I just like what we do with LTCG?

**Comment by RadWolfie** [comment]
> but not all d3d apis are identified. needs further inspection with that particular sample.
> maybe we need a different set of symbol signatures for D3D8I just like what we do with LTCG?

Correct, according to internal discussion D3D8I library is a profiling library. All retail titles doesn't use it since Microsoft will not approve it. However, very few chihiro titles are likely use it and need completely new sets of OOVPA signatures in order to support it. Plus go through verification process to be sure old/new sets of OOVPA signatures do match correctly. Adding D3D8I library support is currently lowest priority at this time.
