### ISSUE TITLE
Missing Detection: D3DDevice_Reset (D3D8LTCG 5849) 

### ISSUE THREAD

**Issue by 0Alastair1** [Cxbx-Reloaded/XbSymbolDatabase#203]
Similar to D3DDevice_Reset_0__LTCG_ebx1 but a bit off.
Addresses found (mapped):
Halo 2 tu0: 0x3f77c0
Halo 2 tu5: 0x4018a0

**Comment by RadWolfie** [comment]
I'm going to assume "tu" stands for title update with a patch number after it. Unfortunately I had not used xbox live to receive these title updates. My ability to research is limited to what's on the retail discs.

**Comment by 0Alastair1** [comment]
Sorry for the confusion. The tu0 version I listed should be the one found on disc.

**Comment by RadWolfie** [comment]
Ah okay, I can confirm the address 0x3f77c0 is starting point of the function for my Halo 2's xbe. And able to confirm it is D3DDevice_Reset function.

**Comment by RadWolfie** [comment]
Hi @0Alastair1, can you please test the binary from pull request #204 to verify D3DDevice_Reset is detected properly for both of your Halo 2's xbes?

**Comment by 0Alastair1** [comment]
Hello, PR detects D3DDevice_Reset on all H2 xbes. Thanks!
