### ISSUE TITLE
Yetisports is probably missing a SetRenderTarget patch

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/XbSymbolDatabase#29]
![image](https://user-images.githubusercontent.com/461930/41108506-fe4532f2-6a74-11e8-8459-4a9bbd07c33f.png)

It's a 5849 title, and it has this in the log :
```
HLECache: 0x00439470 -> D3DDevice_SetRenderTarget	*PATCHED*
HLECache: 0x004396f0 -> D3DDevice_SetRenderTargetFast	*PATCHED*
```

but the white square in the top-left corner seems to indicate it isn't patched correctly...

**Comment by PatrickvL** [comment]
Hm, `D3DDevice_SetRenderTargetFast` actually forwards the call to `D3DDevice_SetRenderTarget`, but that function calls into the Xbox version of  `D3DDevice_SetRenderTarget` via a trampoline, so the behavior of Xbox `D3DDevice_SetRenderTargetFast` is different from what would happen normally.

On the other hand, a breakpoint placed in our `D3DDevice_SetRenderTargetFast` patch never gets hit, so it's not the cause of the strange behaviour...

**Comment by RadWolfie** [comment]
Is Yetisports a LTCG title?

**Comment by PatrickvL** [comment]
There's none

**Comment by RadWolfie** [comment]
Symbol detection is accurate and title is visible in Cxbx-Reloaded emulation. Likely due to further improvement in past years. Closing as not an issue.
