### ISSUE TITLE
TASK: Create simple functions

### ISSUE THREAD

**Issue by RadWolfie** [Cxbx-Reloaded/XbSymbolDatabase#3]
- [ ] Initialize (**on hold,** which also can be used as reset too)
- [X] Scan xbe directly
   * See below for proposal callback function.
   * Currently in complete stage as of commit d2a58bf. However, it will eventually become incomplete later on down the road for need major rework.
- [ ] Scan per ~~library~~ section **(on hold, currently disabled)**
   * See below for proposal callback function.
   * Not recommended to be used at the moment.
- [ ] ~~Scan specific symbol~~ **(Not featured, use callback function to obtain the info during scan process.)**
   * Not recommended at the moment. It does not have unique id like XRef does.
- [X] Register library names, think of it as a whitelist. If it was not called, then use whole libraries in database.
     * `XbSymbolRegisterLibrary(uint32_t library_flag)` for optimize performance.
- [X] Send output strings to program via callback function.
* What else?

Side task:
- [X] Remove global variables from header file since should be only handled internally.

**NOTICE: All export functions should start with XbSymbol.**

Feedback and edits are welcome here.

**Comment by RadWolfie** [comment]
@LukeUsher made an suggestion to perform like this with just only one simple function.
```php
// Individual program use this loop.
foreach(xbe->sections as section) {
    // Then this XbSymbolScan function will perform the task.
    XbSymbolScan(&xbeData, section->name, section->start, section->end, callback_func);
}
```

I, indeed, to agree with this 100%. We will need to make some parameters for the callback_func.
@LukeUsher mentioned something like this.

```c
typedef void (*xb_symbol_callback_t)(char* symbol_name, uint32_t address, uint32_t revision);
bool XbSymbolScan(void* xbeData, char* library_name, uint32_t lower_bound,  uint32_t upper_bound, xb_symbol_callback callback);
```

**Comment by RadWolfie** [comment]
@LukeUsher I'm assigning this task to you as well since you're want to work on Cxbx-Reloaded side.

I am currently working on rename functions, remove global variables accessibility, and create a mockup functions to call scan and callback.

**Comment by RadWolfie** [comment]
Created a PR #12 to prepare getting precise simple API function to work with.

**Comment by RadWolfie** [comment]
Pull request #12 contains
* Remove global variables from header file since should be only handled internally.
* Register library names, think of it as a whitelist. If it was not called, then use whole libraries in database.
* Scan per section.
* Renamed all export functions to start with XbSymbol.

What it does not contain is:
* Initialize internal state. (Which ideally can be used as a reset too.)

**Comment by JayFoxRox** [comment]
This was last edited in May 2018. Is this issue still valid? This project has seen a lot of changes recently.

**Comment by RadWolfie** [comment]
Yes, it doesn't have initialization (or may not require one) and scan per section function are not included yet.

Lots of changes are relative to cross-platform support, include debug support (which finally got moved into this project), and OOVPA changes I think?

**Comment by RadWolfie** [comment]
I have determined move on to design API v3 project.

Closing ticket.

**Comment by JayFoxRox** [comment]
- What does this mean? Was this API v2? And what does that mean? Is that explained anywhere?
- Is the information in the first post still up-to-date / will it be kept updated?
- Is there a new issue to replace this?

It's very hard to keep track of these issues if there's information that's not part of the issues; such as API version information, a long time goal, decisions as to why something is specifically being abandoned.

**Comment by RadWolfie** [comment]
Design API v3 (aka v2.2) will have this ticket's functions implement. The ticket is abandon in favor for #10. Doing the API v3 will make things easier and quicker than re-update most of the stuff all over again.

If you're concern about need to re-update from third-party side, it's very minimal (one or two change).
