### ISSUE TITLE
Wrong recognition

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [Cxbx-Reloaded/XbSymbolDatabase#42]
Situation:
Some titles (GTA San Andreas for example) may refuse to boot and switches to dashboard with that screen:
![image](https://user-images.githubusercontent.com/24764335/45077165-22ac6680-b0f5-11e8-947e-9a23d45d826c.png)

But on recent builds it throws error:
![image](https://user-images.githubusercontent.com/24764335/45077194-36f06380-b0f5-11e8-8783-b3350c3cde29.png)

Crash caused by these two extra lines in HLE/Symbol cache (for example - San Andreas):
D3DDevice_SelectVertexShader_0=35c664
D3DDevice_SetShaderConstantMode_0=35c714

HLE Cache revision is same - 716367461.

**Comment by jarupxx** [comment]
I was confirmed. Fixed by PR #43.
These functions are match standard argument signatures and LTCG specific signatures, so It was necessary to add retn opcode.

**Comment by gandalfthewhite19890404** [comment]
Fixed, closing issue.
