### ISSUE TITLE
Remove global variables

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/XbSymbolDatabase#63]
Concurrent scans requires all global variables to be moved towards a state record, so that all scanning sessions behaves independently from one another.

The way this should work is:

- opening a session allocates a state block and returns a handle
- all scanning functions must be supplied with this handle
- internally, all functions must use the handle to access state variables (where before they were using global variables)
- closing the session releases all resources and frees the state block

**Comment by RadWolfie** [comment]
Aka second stage when #10 task is completed.

**Comment by RadWolfie** [comment]
At this time, we only have two global variables which are only relative to message callback and verbose level.
- g_output_func 
- g_output_verbose_level

Both of these variables are pass into handle's context. Except we cannot remove them. I think it's safe to close this ticket. Do you agree, @PatrickvL?

**Comment by PatrickvL** [comment]
If the goal of concurrent scanning is fully supported now, without any risk of crashing, then it's fine I guess

**Comment by RadWolfie** [comment]
Current affecting functions for having global output callback & message variables are:
- XbSymbolDatabase_GenerateLibraryFilter (does not require context)
- XbSymbolDatabase_TestOOVPAs (no parameters)
- XbSymbolDatabase_CreateXbSymbolContext (required on creation)
  - Both global output variables are pass down to context's handle once on context creation is called.

I don't think these functions do need parameters for output handler. Unless someone made a request for it.

About concurrent scanning fully supported... Yes, it has been fully supported as of API v3. We can safely close this ticket.
