### ISSUE TITLE
OOVPA Symbol Request: DestroyResource

### ISSUE THREAD

**Issue by LukeUsher** [Cxbx-Reloaded/XbSymbolDatabase#82]
DestroyResource in D3D8.LIB is a function that is called internally by the XDK when a resource needs to be freed.

I recently came across a scenario in Cxbx-R where a resource could be erronously freed under certain circumstances. The solution for this issue would require hooking DestroyResource, but currently no OOVPA exists for this.

Requirement for https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/issues/1665

**Comment by LukeUsher** [comment]
Bump: This is also a requirement for properly fixing the Graffiti editor in JSRF, and many occurances of the 'black screen' problem in Cxbx_R

**Comment by PatrickvL** [comment]
Fixed by https://github.com/Cxbx-Reloaded/XbSymbolDatabase/commit/f7143d8db658a40db0c5ab5fe4f7755041c63f30

**Comment by RadWolfie** [comment]
Actually, the proper fix is in pull request #91. PR #90 didn't have LTCG symbol detected.
