### ISSUE TITLE
Select open-source license

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/XbSymbolDatabase#9]
This project will have to be published under some open-source license.
For this issue, discuss, select and apply a license for this project.

Considerations :
* The license must be backwards and forwards compatible with Cxbx-Reloaded

**Comment by LukeUsher** [comment]
If this project used even a single line of code from Cxbx-Reloaded, it MUST stay as GPLv2, otherwise it is a license violation.

**Comment by RadWolfie** [comment]
Open-source license is already applied since it is chained to original licensed by Caustik. We can't change the license without his approval.

Now, can we close this issue?

**Comment by RadWolfie** [comment]
There... IS a LICENSE file. 🙄

**Comment by PatrickvL** [comment]
I'm so sorry, I overlooked that... (that's what you get when doing too many things at the same time)
